[package]
name = "rlcs_predictor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glicko_2 = "1.0.0"
serde = {version = "1.0.158", features = ["derive"]}
serde_json = "1.0.95"